name: "Dive CI"

on: pull_request

jobs:
  dive:
    runs-on: ubuntu-latest
    name: Analyze image efficiency
    steps:
    - uses: actions/checkout@v2
    - name: Build image
      run: docker build -t sample:latest .
    - name: Dive
      uses: yuichielectric/dive-action@migrate-to-typescript
      with:
        image: 'sample:latest'
        github-token: ${{ secrets.GITHUB_TOKEN }}
